import React, { useState } from 'react';
import { Anecdote } from '../types';
import { BookOpen, Lightbulb, Share2, Compass, ToggleLeft, ToggleRight, GraduationCap } from 'lucide-react';

interface AnecdoteCardProps {
  anecdote: Anecdote;
  onRelatedTopicClick: (topic: string) => void;
}

export const AnecdoteCard: React.FC<AnecdoteCardProps> = ({ anecdote, onRelatedTopicClick }) => {
  const [showMeanings, setShowMeanings] = useState(false);

  const handleShare = () => {
    if (navigator.share) {
      navigator.share({
        title: anecdote.title,
        text: `${anecdote.title}\n\n${anecdote.story}\n\nGenerated by Anecdote Academy`,
      }).catch(console.error);
    } else {
      alert("Sharing is not supported on this browser context.");
    }
  };

  const renderStoryWithMeanings = () => {
    if (!showMeanings || !anecdote.toughWords || anecdote.toughWords.length === 0) {
      return anecdote.story;
    }

    // We'll replace the word with a special marker to split the string later
    // Marker format: __MARKER__|word|definition|__MARKER__
    let processedStory = anecdote.story;
    
    // Create a temporary map to hold our replacements to avoid replacing inside already replaced text
    // (though simple iterative replace works if words are distinct)
    const replacements: { start: number, end: number, word: string, definition: string }[] = [];

    anecdote.toughWords.forEach(({ word, definition }) => {
      const regex = new RegExp(`\\b${word}\\b`, 'i');
      const match = regex.exec(processedStory);
      if (match) {
         // We do a simple replaceAll using a unique delimiter logic or just replace
         // Since we want to return React Nodes, we need to split the string.
         // Let's use a simpler approach: replace with a delimited string, then split and map.
         processedStory = processedStory.replace(regex, (m) => `@@@${m}###${definition}@@@`);
      }
    });

    // Now split by the delimiters
    const parts = processedStory.split('@@@');
    
    return parts.map((part, index) => {
      if (part.includes('###')) {
        const [word, definition] = part.split('###');
        return (
          <span key={index} className="text-rose-600 font-semibold bg-rose-50 px-1 rounded mx-0.5">
            {word} <span className="text-rose-500 font-normal italic">({definition})</span>
          </span>
        );
      }
      return <span key={index}>{part}</span>;
    });
  };

  return (
    <div className="w-full bg-white rounded-3xl shadow-xl shadow-slate-200/50 overflow-hidden border border-slate-100 animate-fade-in-up">
      {/* Header Section: Image or Gradient */}
      {anecdote.imageUrl ? (
        <div className="relative h-56 sm:h-64 w-full bg-slate-100">
          <img 
            src={anecdote.imageUrl} 
            alt={anecdote.title} 
            className="w-full h-full object-cover"
          />
          <div className="absolute inset-0 bg-gradient-to-t from-black/90 via-black/30 to-transparent flex flex-col justify-end p-6 text-white">
            <div className="absolute top-4 right-4 bg-white/20 backdrop-blur-md rounded-full p-2 shadow-sm">
               <span className="text-2xl">{anecdote.emoji}</span>
            </div>
            <div className="inline-block px-3 py-1 bg-white/20 backdrop-blur-md rounded-full text-xs font-medium mb-2 self-start">
              {anecdote.topic}
            </div>
            <h2 className="text-2xl font-bold leading-tight drop-shadow-md">{anecdote.title}</h2>
          </div>
        </div>
      ) : (
        <div className="bg-gradient-to-r from-indigo-500 to-purple-600 p-6 text-white relative">
          <div className="absolute top-4 right-4 text-4xl opacity-20 rotate-12">
            {anecdote.emoji}
          </div>
          <div className="inline-block px-3 py-1 bg-white/20 backdrop-blur-md rounded-full text-xs font-medium mb-3">
            {anecdote.topic}
          </div>
          <h2 className="text-2xl font-bold leading-tight">{anecdote.title}</h2>
        </div>
      )}

      <div className="p-6 space-y-6">
        
        {/* Story Controls */}
        <div className="flex justify-end">
           <button 
             onClick={() => setShowMeanings(!showMeanings)}
             className="flex items-center gap-2 text-xs font-semibold text-slate-500 hover:text-indigo-600 transition-colors"
           >
             {showMeanings ? (
               <ToggleRight className="w-6 h-6 text-indigo-600" />
             ) : (
               <ToggleLeft className="w-6 h-6 text-slate-300" />
             )}
             Show Meanings
           </button>
        </div>

        {/* Main Story Text */}
        <div className="prose prose-slate leading-relaxed text-slate-600 relative">
          <p className="whitespace-pre-line text-lg">
            {renderStoryWithMeanings()}
          </p>
        </div>

        {/* Fun Fact */}
        <div className="bg-amber-50 rounded-2xl p-5 border border-amber-100">
          <div className="flex items-start gap-3">
            <Lightbulb className="w-5 h-5 text-amber-500 mt-0.5 flex-shrink-0" />
            <div>
              <h3 className="text-sm font-bold text-amber-800 uppercase tracking-wide mb-1">Did you know?</h3>
              <p className="text-amber-900/80 text-sm">{anecdote.funFact}</p>
            </div>
          </div>
        </div>

        {/* Takeaway */}
        <div className="bg-slate-50 rounded-2xl p-5 border border-slate-100">
          <div className="flex items-start gap-3">
            <BookOpen className="w-5 h-5 text-indigo-500 mt-0.5 flex-shrink-0" />
            <div>
              <h3 className="text-sm font-bold text-indigo-800 uppercase tracking-wide mb-1">Key Takeaway</h3>
              <p className="text-slate-600 text-sm">{anecdote.takeaway}</p>
            </div>
          </div>
        </div>

        {/* NCERT Topic */}
        {anecdote.ncertTopic && (
          <div className="flex items-center gap-2 text-slate-500 bg-slate-50 px-4 py-2 rounded-lg border border-slate-100">
            <GraduationCap className="w-5 h-5 text-indigo-600" />
            <span className="text-xs font-bold uppercase tracking-wider text-slate-400">Syllabus:</span>
            <span className="text-sm font-medium text-slate-700">{anecdote.ncertTopic}</span>
          </div>
        )}

        {/* Related Topics */}
        {anecdote.relatedTopics && anecdote.relatedTopics.length > 0 && (
          <div className="pt-2">
            <div className="flex items-center gap-2 mb-3 text-slate-400">
              <Compass className="w-4 h-4" />
              <span className="text-xs font-medium uppercase tracking-wider">Curious for more?</span>
            </div>
            <div className="flex flex-wrap gap-2">
              {anecdote.relatedTopics.map((topic, index) => (
                <button
                  key={index}
                  onClick={() => onRelatedTopicClick(topic)}
                  className="px-4 py-2 bg-indigo-50 hover:bg-indigo-100 text-indigo-700 text-sm font-medium rounded-full transition-colors border border-indigo-100"
                >
                  {topic}
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Footer Actions */}
        <div className="flex justify-end pt-4 border-t border-slate-100">
          <button 
            onClick={handleShare}
            className="flex items-center text-slate-400 hover:text-indigo-600 text-sm font-medium transition-colors"
          >
            <Share2 className="w-4 h-4 mr-2" />
            Share Story
          </button>
        </div>
      </div>
    </div>
  );
};